### ISSUE TITLE
Release the updated 1.20.1

### ISSUE THREAD

**Issue by Zorklis** [trufflezmc/skip-transitions#11]
So there was a commit that supposedly updated the depencies (see https://github.com/trufflezmc/skip-transitions/pull/10) but we are still missing the release.
https://github.com/trufflezmc/skip-transitions/releases and the last one was in 2022

**Comment by TGODiamond** [comment]
I tested the build before opening the pr, so only a release is needed now

**Comment by trufflezmc** [comment]
Release made
